export const GET_SERVICES = "GET_SERVICES";
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const GET_SERVICES_FAILURE = "GET_SERVICES_FAILURE";
export const SEARCH_SERVICES = "SEARCH_SERVICES";
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const FILTER_BY_STATUS = "FILTER_BY_STATUS";
export const GET_SERVICES_INIT = "GET_SERVICES_INIT";
